### ISSUE TITLE
TODO: Upload pre-trained weights

### ISSUE THREAD

**Issue by jszym** [Emad-COMBINE-lab/intrepppid#3]
Pre-trained weights have not been uploaded, making inference impossible without first training a model, which is needless. This was brought up in #1 .

I need to upload the weights used in the manuscript.

**Comment by Rohit-Satyam** [comment]
Hi,

I was wondering if you uploaded pre-trained weights already?

**Comment by jszym** [comment]
Hi there! So sorry for the long wait. You can now download the weights used in our pre-print on the [releases](https://github.com/Emad-COMBINE-lab/intrepppid/releases/tag/preprint-v1) page (they are in the file `weights.zip`).

I'll also be posting an update that will add an `infer` command to INTREPPPID's CLI, making using these weights a lot simpler. That update should come a lot quicker.
